version: "3"
services:
  westminster_mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - westminster_mongodb:/data/db
    ports:
      - '27017-27019:27017-27019'
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    volumes:
      - /var/www/node_modules
      - ../../frontend:/var/www/
    ports:
      - '3000:3000'
  backend:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - '4567:4567'
    depends_on:
      - westminster_mongodb
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: westminster_mongodb
      MONGODB_DATABASE: ${MONGODB_DATABASE}
volumes:
  westminster_mongodb: